# Generated by Django 5.1.3 on 2024-11-08 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TeamSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_t1', models.CharField(max_length=100)),
                ('driver_t2_1', models.CharField(max_length=100)),
                ('driver_t2_2', models.CharField(max_length=100)),
                ('driver_t2_3', models.CharField(max_length=100)),
                ('driver_t2_4', models.CharField(max_length=100)),
                ('driver_t2_5', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.race')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
