# Generated by Django 5.1.3 on 2024-11-08 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('position', models.IntegerField()),
                ('points', models.IntegerField(default=0)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.race')),
            ],
        ),
    ]
