# Generated by Django 5.1.3 on 2024-11-11 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_raceresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceresult',
            name='dnf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='raceresult',
            name='driver_tier',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='raceresult',
            name='fastest_lap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='raceresult',
            name='session_type',
            field=models.CharField(choices=[('Qualifying', 'Qualifying'), ('Race', 'Race'), ('Sprint', 'Sprint')], default='Qualifying', max_length=10),
        ),
    ]
