# Generated by Django 5.1.3 on 2024-11-11 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_raceresult_dnf_raceresult_driver_tier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('standing', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='raceresult',
            name='driver_name',
        ),
        migrations.RemoveField(
            model_name='raceresult',
            name='driver_tier',
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='session_type',
            field=models.CharField(choices=[('Qualifying', 'Qualifying'), ('Race', 'Race'), ('Sprint', 'Sprint')], max_length=10),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tier', models.IntegerField(choices=[(1, 'Tier 1'), (2, 'Tier 2')])),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='league.constructor')),
            ],
        ),
        migrations.AddField(
            model_name='raceresult',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='league.driver'),
        ),
    ]
