# Generated by Django 5.1.3 on 2024-11-11 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_constructor_remove_raceresult_driver_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='price',
            field=models.IntegerField(default=1),
        ),
    ]
