# Generated by Django 5.1.3 on 2024-11-11 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_driver_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamselection',
            name='driver_t1',
        ),
        migrations.RemoveField(
            model_name='teamselection',
            name='driver_t2_1',
        ),
        migrations.RemoveField(
            model_name='teamselection',
            name='driver_t2_2',
        ),
        migrations.RemoveField(
            model_name='teamselection',
            name='driver_t2_3',
        ),
        migrations.RemoveField(
            model_name='teamselection',
            name='driver_t2_4',
        ),
        migrations.RemoveField(
            model_name='teamselection',
            name='driver_t2_5',
        ),
        migrations.RemoveField(
            model_name='teamselection',
            name='points',
        ),
        migrations.RemoveField(
            model_name='teamselection',
            name='team',
        ),
        migrations.AddField(
            model_name='teamselection',
            name='drivers',
            field=models.ManyToManyField(related_name='team_selections', to='league.driver'),
        ),
        migrations.AddField(
            model_name='teamselection',
            name='submitted_on_time',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teamselection',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
