# Generated by Django 5.1.3 on 2024-11-11 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0008_alter_team_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='league.league'),
        ),
    ]
