# Generated by Django 5.1.3 on 2024-11-12 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0009_alter_team_league'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='league.league'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('user', 'league')},
        ),
    ]
