# Generated by Django 5.1.3 on 2024-11-12 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0010_alter_team_league_alter_team_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='season',
            field=models.IntegerField(default=2024),
        ),
    ]
