# Generated by Django 5.1.3 on 2024-11-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0011_race_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driver_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='driver',
            name='tier',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
