# Generated by Django 5.1.3 on 2024-11-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0012_driver_driver_id_driver_nationality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='circuit',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='round',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
