# Generated by Django 5.1.3 on 2024-11-12 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0013_race_circuit_race_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='constructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='league.constructor'),
        ),
    ]
