# Generated by Django 5.1.3 on 2024-11-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0014_alter_driver_constructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructor',
            name='standing',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
