# Generated by Django 5.1.3 on 2024-11-13 15:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0015_alter_constructor_standing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='users',
            field=models.ManyToManyField(related_name='leagues', to=settings.AUTH_USER_MODEL),
        ),
    ]
