# Generated by Django 5.1.3 on 2024-11-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0016_league_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamselection',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
