# Generated by Django 5.1.3 on 2024-11-13 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0017_teamselection_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceresult',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='race_results', to='league.driver'),
        ),
    ]
