# Generated by Django 5.1.3 on 2024-11-14 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0018_alter_raceresult_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='circuit',
        ),
        migrations.RemoveField(
            model_name='race',
            name='date',
        ),
        migrations.RemoveField(
            model_name='race',
            name='location',
        ),
        migrations.RemoveField(
            model_name='race',
            name='name',
        ),
        migrations.RemoveField(
            model_name='race',
            name='round',
        ),
        migrations.RemoveField(
            model_name='race',
            name='season',
        ),
        migrations.AddField(
            model_name='race',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races', to='league.league'),
        ),
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='league.league'),
        ),
        migrations.AlterField(
            model_name='teamselection',
            name='drivers',
            field=models.ManyToManyField(related_name='drivers', to='league.driver'),
        ),
        migrations.AlterField(
            model_name='teamselection',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_selections', to='league.race'),
        ),
        migrations.AlterField(
            model_name='teamselection',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='league.team'),
        ),
        migrations.AlterUniqueTogether(
            name='teamselection',
            unique_together={('team', 'race')},
        ),
        migrations.CreateModel(
            name='RaceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('season', models.IntegerField(default=2024)),
                ('round', models.IntegerField()),
                ('circuit', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'unique_together': {('season', 'round')},
            },
        ),
        migrations.AddField(
            model_name='race',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races', to='league.racetemplate'),
        ),
    ]
