# Generated by Django 5.1.3 on 2024-11-15 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0019_remove_race_circuit_remove_race_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalConstructorStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standing', models.IntegerField()),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.constructor')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_standings', to='league.race')),
            ],
            options={
                'unique_together': {('race', 'constructor')},
            },
        ),
    ]
