# Generated by Django 5.1.3 on 2024-11-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0020_historicalconstructorstanding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceresult',
            name='points',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='teamselection',
            name='points',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
