# Generated by Django 5.1.3 on 2024-11-17 22:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0021_alter_raceresult_points_alter_teamselection_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('question_type', models.CharField(choices=[('text', 'Text'), ('multiple_choice', 'Multiple Choice')], max_length=50)),
                ('options', models.JSONField(blank=True, null=True)),
                ('points_awarded', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5)),
                ('correct_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('race', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_question', to='league.race')),
            ],
        ),
        migrations.CreateModel(
            name='PredictionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
                ('points_earned', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5)),
                ('is_correct', models.BooleanField(default=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_answers', to='league.team')),
                ('prediction_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='league.predictionquestion')),
            ],
        ),
    ]
