# Generated by Django 5.1.3 on 2024-11-17 22:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0023_alter_predictionquestion_points_awarded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionanswer',
            name='points_earned',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.0'), max_digits=5),
        ),
    ]
