# Generated by Django 5.1.3 on 2024-11-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0024_alter_predictionanswer_points_earned'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceresult',
            name='is_tier_override',
            field=models.BooleanField(default=False),
        ),
    ]
