name: CI/CD Workflow

on:
  push:
    branches:
      - dev
      - master
  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up SSH for Dev
        run: |
          mkdir -p ~/.ssh
          printf "%s\n" "${{ secrets.DEV_LXC_SSH_KEY }}" > ~/.ssh/id_ed25519_dev
          chmod 600 ~/.ssh/id_ed25519_dev
          ssh-keyscan -H "${{ secrets.DEV_LXC_IP }}" >> ~/.ssh/known_hosts

      - name: Debug SSH Key
        run: |
          echo "IP Address: ${{ secrets.DEV_LXC_IP }}"
          echo "Checking SSH Key Directory:"
          ls -la ~/.ssh
          echo "Preview SSH Key Content:"
          head -n 5 ~/.ssh/id_ed25519_dev

      - name: Deploy to Dev
        run: |
          ssh -i ~/.ssh/id_ed25519_dev root@${{ secrets.DEV_LXC_IP }} "cd /f1-fantasy && docker-compose up -d"
          
  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-dev
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up SSH for Prod
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PROD_LXC_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.PROD_LXC_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Prod
        run: |
          ssh root@${{ secrets.PROD_LXC_IP }} "cd /root/f1_fantasy_project && git pull origin master && docker-compose down && docker-compose up -d"
