name: CI/CD Workflow

on:
  push:
    branches:
      - dev
      - master
  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
      - name: Debug SSH Environment
        run: |
          echo "IP Address: ${{ secrets.DEV_LXC_IP }}"
          printf "SSH Key Content: $(head -n 2 ~/.ssh/id_ed25519_dev)"  # Only show the first two lines for security
          ssh-keyscan -H ${{ secrets.DEV_LXC_IP }}
      - name: Set up SSH for Dev
        run: |
          set -x
          mkdir -p ~/.ssh
          printf "%s" "${{ secrets.DEV_LXC_SSH_KEY }}" > ~/.ssh/id_ed25519_dev
          chmod 600 ~/.ssh/id_ed25519_dev
          ssh-keyscan -H "${{ secrets.DEV_LXC_IP }}" >> ~/.ssh/known_hosts

      - name: Deploy to Dev
        run: |
          ssh root@${{ secrets.DEV_LXC_IP }} "cd /f1-fantasy && git pull origin dev && docker-compose down && docker-compose up -d"

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-dev
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up SSH for Prod
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PROD_LXC_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.PROD_LXC_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Prod
        run: |
          ssh root@${{ secrets.PROD_LXC_IP }} "cd /root/f1_fantasy_project && git pull origin master && docker-compose down && docker-compose up -d"
